version: '3.8'

services:
  frontend:
    build:
      context: ./Ping-Pong-FrontEnd
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/app/build
    command: echo "Frontend build complete."
    environment:
      - REACT_APP_API_URL=/api
      - REACT_APP_WEBSOCKET_API_URL=/ws/chat
    depends_on:
      - backend

  backend:
    build:
      context: ./Ping-Pong-Backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1d & wait $${!}; done'"
    restart: unless-stopped

volumes:
  frontend_build:                                                      