version: '3.8'

services:
  frontend:
    build:
      context: ./Ping-Pong-FrontEnd
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=/api
      - REACT_APP_WEBSOCKET_API_URL=/ws/chat
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./Ping-Pong-Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    restart: unless-stopped